<?xml version="1.0" encoding="utf-8"?><Database Name="QUANLYTRASUA" Class="QUANLYQUANTRADataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-SH243I1\LETHIKIMLE;Initial Catalog=QUANLYTRASUA;Integrated Security=True" SettingsObjectName="QuanLyQuanTraSua.Properties.Settings" SettingsPropertyName="QUANLYTRASUAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BANGLUONG" Member="BANGLUONGs">
    <Type Name="BANGLUONG">
      <Column Name="Nam" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Thang" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNV" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TienLuong" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Association Name="NHANVIEN_BANGLUONG" Member="NHANVIEN" ThisKey="MaNV" OtherKey="MaNV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CALAM" Member="CALAMs">
    <Type Name="CALAM">
      <Column Name="MaCa" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ThoiGianBatDau" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="ThoiGianKetThuc" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="LuongTheoGio" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="NhanVienToiDa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CALAM_QUANLYLUONG" Member="QUANLYLUONGs" ThisKey="MaCa" OtherKey="MaCa" Type="QUANLYLUONG" />
    </Type>
  </Table>
  <Table Name="dbo.CHI" Member="CHIs">
    <Type Name="CHI">
      <Column Name="Nam" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Thang" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LuongNV" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="PhiNguyenLieu" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="TienDien" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="TienNuoc" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="PhiVeSinh" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="Tong" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Association Name="CHI_LOINHUAN" Member="LOINHUAN" ThisKey="Nam,Thang" OtherKey="Nam,Thang" Type="LOINHUAN" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETHOADON" Member="CHITIETHOADONs">
    <Type Name="CHITIETHOADON">
      <Column Name="MaHD" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaMH" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tien" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="DiemTichLuy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HOADON_CHITIETHOADON" Member="HOADON" ThisKey="MaHD" OtherKey="MaHD" Type="HOADON" IsForeignKey="true" />
      <Association Name="MENU_CHITIETHOADON" Member="MENU" ThisKey="MaMH" OtherKey="MaMH" Type="MENU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.COUPON" Member="COUPONs">
    <Type Name="COUPON">
      <Column Name="MaCP" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NgayBatDau" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NgayKetThuc" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DiemApDung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MucGiam" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="GiamToiDa" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Association Name="COUPON_HOADON" Member="HOADONs" ThisKey="MaCP" OtherKey="MaCP" Type="HOADON" />
    </Type>
  </Table>
  <Table Name="dbo.DANGNHAP" Member="DANGNHAPs">
    <Type Name="DANGNHAP">
      <Column Name="MaTK" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaND" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenDangNhap" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="QUANLY_DANGNHAP" Member="QUANLY" ThisKey="MaND" OtherKey="MaQL" Type="QUANLY" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DANGNHAP2" Member="DANGNHAP2s">
    <Type Name="DANGNHAP2">
      <Column Name="MaTK" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaND" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenDangNhap" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="NHANVIEN_DANGNHAP2" Member="NHANVIEN" ThisKey="MaND" OtherKey="MaNV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DOANHTHU" Member="DOANHTHUs">
    <Type Name="DOANHTHU">
      <Column Name="Nam" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Thang" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DoanhThu" Member="DoanhThu1" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="SoDonHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DOANHTHU_LOINHUAN" Member="LOINHUAN" ThisKey="Nam,Thang" OtherKey="Nam,Thang" Type="LOINHUAN" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MaHD" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaNV" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ThanhTien" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="NgayXuatHD" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="MaCP" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="HOADON_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="MaHD" OtherKey="MaHD" Type="CHITIETHOADON" />
      <Association Name="COUPON_HOADON" Member="COUPON" ThisKey="MaCP" OtherKey="MaCP" Type="COUPON" IsForeignKey="true" />
      <Association Name="KHACHHANG_HOADON" Member="KHACHHANG" ThisKey="MaKH" OtherKey="MaKH" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="NHANVIEN_HOADON" Member="NHANVIEN" ThisKey="MaNV" OtherKey="MaNV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MaKH" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiemTichLuy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="KHACHHANG_HOADON" Member="HOADONs" ThisKey="MaKH" OtherKey="MaKH" Type="HOADON" />
    </Type>
  </Table>
  <Table Name="dbo.MENU" Member="MENUs">
    <Type Name="MENU">
      <Column Name="MaMH" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenMH" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="GiaTien" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="DiemTichLuy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MENU_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="MaMH" OtherKey="MaMH" Type="CHITIETHOADON" />
    </Type>
  </Table>
  <Table Name="dbo.LOINHUAN" Member="LOINHUANs">
    <Type Name="LOINHUAN">
      <Column Name="Nam" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Thang" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DoanhThu" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="ChiPhi" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="LoiNhuan" Member="LoiNhuan1" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Association Name="CHI_LOINHUAN" Member="CHI" ThisKey="Nam,Thang" OtherKey="Nam,Thang" Type="CHI" IsForeignKey="true" />
      <Association Name="DOANHTHU_LOINHUAN" Member="DOANHTHU1" ThisKey="Nam,Thang" OtherKey="Nam,Thang" Type="DOANHTHU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MaNV" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgayNV" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="CMND" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ConLam" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="NHANVIEN_BANGLUONG" Member="BANGLUONGs" ThisKey="MaNV" OtherKey="MaNV" Type="BANGLUONG" />
      <Association Name="NHANVIEN_DANGNHAP2" Member="DANGNHAP2s" ThisKey="MaNV" OtherKey="MaND" Type="DANGNHAP2" />
      <Association Name="NHANVIEN_HOADON" Member="HOADONs" ThisKey="MaNV" OtherKey="MaNV" Type="HOADON" />
      <Association Name="NHANVIEN_QUANLYLUONG" Member="QUANLYLUONGs" ThisKey="MaNV" OtherKey="MaNV" Type="QUANLYLUONG" />
    </Type>
  </Table>
  <Table Name="dbo.QUANLY" Member="QUANLies">
    <Type Name="QUANLY">
      <Column Name="MaQL" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenQL" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CMND" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="QUANLY_DANGNHAP" Member="DANGNHAPs" ThisKey="MaQL" OtherKey="MaND" Type="DANGNHAP" />
    </Type>
  </Table>
  <Table Name="dbo.QUANLYLUONG" Member="QUANLYLUONGs">
    <Type Name="QUANLYLUONG">
      <Column Name="ThoiGian" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNV" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaCa" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MucDoHoanThanh" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="Luong" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Association Name="CALAM_QUANLYLUONG" Member="CALAM" ThisKey="MaCa" OtherKey="MaCa" Type="CALAM" IsForeignKey="true" />
      <Association Name="NHANVIEN_QUANLYLUONG" Member="NHANVIEN" ThisKey="MaNV" OtherKey="MaNV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
</Database>