//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanTraSua
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CALAM()
        {
            this.QUANLYLUONGs = new HashSet<QUANLYLUONG>();
        }
    
        public string MaCa { get; set; }
        public Nullable<System.TimeSpan> ThoiGianBatDau { get; set; }
        public Nullable<System.TimeSpan> ThoiGianKetThuc { get; set; }
        public double LuongTheoGio { get; set; }
        public Nullable<int> NhanVienToiDa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUANLYLUONG> QUANLYLUONGs { get; set; }
    }
}
