//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanTraSua
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI
    {
        public int Nam { get; set; }
        public int Thang { get; set; }
        public Nullable<float> LuongNV { get; set; }
        public Nullable<float> PhiNguyenLieu { get; set; }
        public Nullable<float> TienDien { get; set; }
        public Nullable<float> TienNuoc { get; set; }
        public Nullable<float> PhiVeSinh { get; set; }
        public Nullable<float> Tong { get; set; }
    
        public virtual LOINHUAN LOINHUAN { get; set; }
    }
}
