//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanTraSua
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANGNHAP
    {
        public string MaTK { get; set; }
        public string MaND { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
    
        public virtual QUANLY QUANLY { get; set; }
    }
}
