//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanTraSua
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOINHUAN
    {
        public int Nam { get; set; }
        public int Thang { get; set; }
        public Nullable<float> DoanhThu { get; set; }
        public Nullable<float> ChiPhi { get; set; }
        public Nullable<float> LoiNhuan1 { get; set; }
    
        public virtual CHI CHI { get; set; }
        public virtual DOANHTHU DOANHTHU1 { get; set; }
    }
}
